# Generated by Django 4.2 on 2025-01-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='confirmacionPreciosModulo',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='cotizadorModulo',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='pdfsModulo',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='tramiteModulo',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
