# Generated by Django 4.2 on 2025-01-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_cotizador_confirmacionpreciosmodulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='cotizador_confirm_price/'),
        ),
    ]
