# Generated by Django 4.2 on 2025-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_cotizador_confirmacionpreciosmodulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='idEtiqueta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
