# Generated by Django 4.2 on 2025-02-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_cotizador_idetiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='idBanco',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
