# Generated by Django 4.2 on 2025-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_cotizador_idbanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizador',
            name='idBanco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
