# Generated by Django 4.2 on 2025-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_cotizador_fechatramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='sendToArchivo',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
