# Generated by Django 4.2 on 2025-04-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_cotizador_sendtoarchivo'),
        ('proveedores', '0001_initial'),
        ('fichaproveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalProveedor',
            new_name='FichaProveedor',
        ),
    ]
