# Generated by Django 4.2 on 2025-08-11 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_etiqueta'),
        ('fichaproveedor', '0002_rename_finalproveedor_fichaproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaProveedorPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoProveedor', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
