# Generated by Django 4.2 on 2025-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idCliente', models.IntegerField()),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=10)),
                ('antiguoValor', models.TextField()),
                ('nuevoValor', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idCliente', models.IntegerField()),
                ('etiquetaUno', models.CharField(max_length=255)),
                ('etiquetaDos', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=50)),
                ('cilindraje', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50)),
                ('numeroDocumento', models.CharField(max_length=50)),
                ('nombreCompleto', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('pagoInmediato', models.BooleanField()),
                ('precioDeLey', models.CharField(max_length=255)),
                ('comisionPrecioLey', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
