# Generated by Django 4.2 on 2025-01-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='comisionPrecioLey',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='etiquetaDos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='etiquetaUno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='pagoInmediato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='precioDeLey',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='total',
            field=models.CharField(default='', max_length=255),
        ),
    ]
