# Generated by Django 4.2 on 2025-01-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_alter_tramite_comisionprecioley_alter_tramite_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tipoDocumento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
