# Generated by Django 4.2 on 2025-01-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_tramite_linkpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/pdfs/'),
        ),
    ]
