# Generated by Django 4.2 on 2025-01-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_logtramite_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('Recepción', 'Recepción'), ('Validación', 'Validación'), ('Ejecución', 'Ejecución'), ('Finalización', 'Finalización')], default='Recepción', max_length=50),
        ),
    ]
