# Generated by Django 4.2 on 2025-01-25 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_tramite_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
