# Generated by Django 4.2 on 2025-09-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustesaldos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ajustesaldo',
            table='ajustesaldo',
        ),
    ]
