# Generated by Django 4.2 on 2025-08-24 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registroTarjetas', '0004_registrotarjetas_is_daviplata'),
        ('clientes', '0003_alter_cliente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargosnodesados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Ingreso')),
                ('fecha_transaccion', models.DateField(verbose_name='Fecha de Transacción')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('cuatro_por_mil', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('id_tarjeta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroTarjetas.registrotarjetas', verbose_name='Cuenta Bancaria Origen')),
            ],
            options={
                'verbose_name': 'Cargosnodeseado',
                'verbose_name_plural': 'Cargosnodeseados',
                'db_table': 'cargosnodeseados',
            },
        ),
    ]
