# Generated by Django 4.2 on 2025-08-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_nombre'),
        ('cargosnoregistrados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargosnodesados',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
