# Generated by Django 4.2 on 2025-02-21 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
        ('registroTarjetas', '0003_alter_registrotarjetas_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastogenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Ingreso')),
                ('fecha_transaccion', models.DateField(verbose_name='Fecha de Transacción')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('id_tarjeta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroTarjetas.registrotarjetas', verbose_name='Cuenta Bancaria Origen')),
                ('id_tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gastos')),
            ],
            options={
                'verbose_name': 'Gasto general',
                'verbose_name_plural': 'Gastos generales',
            },
        ),
    ]
