# Generated by Django 4.2 on 2025-09-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolucion', '0002_alter_devolucion_valor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devolucion',
            table='devolucion_devolucion',
        ),
    ]
