# Generated by Django 4.2 on 2025-02-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=40, unique=True)),
                ('nombre_cuenta', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('saldo', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tarjetas/')),
            ],
        ),
    ]
