# Generated by Django 4.2 on 2025-02-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroTarjetas', '0002_registrotarjetas_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotarjetas',
            name='saldo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
