# Generated by Django 4.2 on 2025-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroTarjetas', '0003_alter_registrotarjetas_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotarjetas',
            name='is_daviplata',
            field=models.BooleanField(default=False),
        ),
    ]
