# Generated by Django 4.2 on 2025-09-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroTarjetas', '0004_registrotarjetas_is_daviplata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrotarjetas',
            table='registrotarjetas_registrotarjetas',
        ),
    ]
