# Generated by Django 4.2 on 2025-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasbancarias', '0002_rename_nombre_cuenta_cuentabancaria_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fechaIngreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
