# Generated by Django 4.2 on 2025-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasbancarias', '0003_alter_cuentabancaria_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuatro_por_mil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
