# Generated by Django 4.2 on 2025-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidadocacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilidadocacional',
            name='cuatro_por_mil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
