# Generated by Django 4.2 on 2025-02-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
