# Generated by Django 4.2 on 2025-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='medio_contacto',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
