# Generated by Django 4.2 on 2025-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_alter_devoluciones_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciones',
            name='cuatro_por_mil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
