# Generated by Django 4.2 on 2025-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0003_devoluciones_cuatro_por_mil'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devoluciones',
            table='devoluciones_devoluciones',
        ),
    ]
