# Generated by Django 4.2 on 2025-02-20 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
