# Generated by Django 4.2 on 2025-08-30 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registroTarjetas', '0004_registrotarjetas_is_daviplata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetastrasladofondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Ingreso')),
                ('fecha_transaccion', models.DateField(verbose_name='Fecha de Transacción')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('cuatro_por_mil', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('id_tarjeta_bancaria_envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_enviados', to='registroTarjetas.registrotarjetas', verbose_name='Cuenta Bancaria Envia')),
                ('id_tarjeta_bancaria_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_recibidos', to='registroTarjetas.registrotarjetas', verbose_name='Cuenta Bancaria Recibe')),
            ],
            options={
                'verbose_name': 'Tarjetastrasladofondo',
                'verbose_name_plural': 'tarjetastrasladofondos',
                'db_table': 'tarjetastrasladofondo',
            },
        ),
    ]
