# Generated by Django 4.2 on 2025-08-31 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetastrasladofondo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetastrasladofondo',
            name='fecha_transaccion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Transacción'),
        ),
    ]
