# Generated by Django 4.2 on 2025-02-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionPago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recepcionpago',
            table='recepcionPago_recepcionpago',
        ),
    ]
