# Generated by Django 4.2 on 2025-02-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroTarjetas', '0003_alter_registrotarjetas_saldo'),
        ('recepcionPago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionpago',
            name='cuenta_bancaria_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroTarjetas.registrotarjetas', verbose_name='RegistroTarjetas'),
        ),
    ]
