# Generated by Django 4.2 on 2025-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionPago', '0002_alter_recepcionpago_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionpago',
            name='fecha_transaccion',
            field=models.DateTimeField(verbose_name='Fecha de Transacción'),
        ),
    ]
