# Generated by Django 4.2 on 2025-02-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionPago', '0002_alter_recepcionpago_cuenta_bancaria_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcionpago',
            old_name='cuenta_bancaria_destino',
            new_name='id_tarjeta_bancaria',
        ),
    ]
