# Generated by Django 4.2 on 2025-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionPago', '0003_rename_cuenta_bancaria_destino_recepcionpago_id_tarjeta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionpago',
            name='valor',
            field=models.TextField(verbose_name='Valor'),
        ),
    ]
